= 对象存储(OSS)-配置使用手册
Qu Songtao;
v1.0.0
:lang: zh-cmn-Hans
:doctype: book
:description: 对象存储(OSS)-配置使用手册
:icons: font
:source-highlighter: highlightjs
:linkcss!:
:numbered:
:idprefix:
:toc: left
:toc-title: 导航目录
:toclevels: 3
:experimental:

目的：文件存储、对象存储，目前支持500M以下的文件。

项目源代码地址: http://10.163.189.85:9090/pms/oss-api-service[GitLab:oss-api-service]

== 基础配置

=== maven依赖
[source,xml]
----
<!--feign config-->
<dependency>
    <groupId>io.github.openfeign.form</groupId>
    <artifactId>feign-form</artifactId>
    <version>2.2.1</version>
</dependency>
<dependency>
    <groupId>io.github.openfeign.form</groupId>
    <artifactId>feign-form-spring</artifactId>
    <version>2.2.1</version>
</dependency>
<dependency>
    <groupId>io.github.openfeign</groupId>
    <artifactId>feign-core</artifactId>
    <version>9.5.1</version>
</dependency>
----

=== Feign Encoder配置类
[source,java]
----
import feign.form.spring.SpringFormEncoder;
import feign.codec.Encoder;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Primary;
import org.springframework.context.annotation.Scope;
@Configuration
public class FeignConfig {
    @Bean
    @Primary
    @Scope("prototype")
    public Encoder multipartFormEncoder() {
        return new SpringFormEncoder();
    }
}
----

== 接口及示例
对象存储服务名称: #oss-api-service#

=== 接口API说明

==== 文件上传-MultipartFile
[source,http,options="nowrap"]
----
POST /file/upload/multiPartFile HTTP/1.1
----

[cols="1,1,4", options="header"]
.请求参数
|===
|参数|类型|描述

|`sysCode`
|String
|约定系统编码, #(必填)# ["pms","epm","usercenter","progress","portal","collect"],除此之外的由管理员补充

|`fileGroupId`
|String
|文件组ID,相当于文件夹,36位UUID #(必填)#

|`fileId`
|String
|文件ID,36位UUID #(必填)#

|`file`
|MultipartFile
|MultipartFile #(必填)#

|===

[cols="1,1,4", options="header"]
.响应结果
|===
|参数|类型|描述

|`Response`
|Response
|com.lensyn.common.utils.system.response.Response文字描述上传结果

|===

==== 文件上传-byte[]
[source,http,options="nowrap"]
----
POST /file/upload/bytes HTTP/1.1
----

[cols="1,1,4", options="header"]
.请求参数
|===
|参数|类型|描述

|`sysCode`
|String
|约定系统编码, #(必填)# ["pms","epm","usercenter","progress","portal","collect"],除此之外的由管理员补充

|`fileGroupId`
|String
|文件组ID,相当于文件夹,36位UUID #(必填)#

|`fileId`
|String
|文件ID,36位UUID #(必填)#

|`fileName`
|String
|文件名称 #(必填)#,如:XXX质量报告.docx

|`file`
|byte[]
|byte[]对象 #(必填)#,针对小文件可以转成byte[],大文件转byte[]传输会导致内存溢出

|===

[cols="1,1,4", options="header"]
.响应结果
|===
|参数|类型|描述

|`Response`
|Response
|com.lensyn.common.utils.system.response.Response文字描述上传结果

|===

==== 文件上传-InputStream
[source,http,options="nowrap"]
----
POST /file/upload/inputStream HTTP/1.1
----

[cols="1,1,4", options="header"]
.请求参数
|===
|参数|类型|描述

|`sysCode`
|String
|约定系统编码, #(必填)# ["pms","epm","usercenter","progress","portal","collect"],除此之外的由管理员补充

|`fileGroupId`
|String
|文件组ID,相当于文件夹,36位UUID #(必填)#

|`fileId`
|String
|文件ID,36位UUID #(必填)#

|`fileName`
|String
|文件名称 #(必填)#,如:XXX质量报告.docx

|`file`
|InputStream
|文件输入流对象 #(必填)#

|===

[cols="1,1,4", options="header"]
.响应结果
|===
|参数|类型|描述

|`Response`
|Response
|com.lensyn.common.utils.system.response.Response文字描述上传结果

|===

==== 文件名称获取
[source,http,options="nowrap"]
----
GET /file/info HTTP/1.1
----

[cols="1,1,4", options="header"]
.请求参数
|===
|参数|类型|描述

|`sysCode`
|String
|约定系统编码, #(必填)# ["pms","epm","usercenter","progress","portal","collect"],除此之外的由管理员补充

|`fileGroupId`
|String
|文件组ID,相当于文件夹,36位UUID #(必填)#

|`fileId`
|String
|文件ID,36位UUID #(必填)#

|===

[cols="1,1,4", options="header"]
.响应结果
|===
|参数|类型|描述

|`Response`
|Response
|返回文件名称,如:XXX质量报告.docx

|===


==== 文件下载
[source,http,options="nowrap"]
----
POST /file/download HTTP/1.1
----

[cols="1,1,4", options="header"]
.请求参数
|===
|参数|类型|描述

|`sysCode`
|String
|约定系统编码, #(必填)# ["pms","epm","usercenter","progress","portal","collect"],除此之外的由管理员补充

|`fileGroupId`
|String
|文件组ID,相当于文件夹,36位UUID #(必填)#

|`fileId`
|String
|文件ID,36位UUID #(必填)#

|===

[cols="1,1,4", options="header"]
.响应结果
|===
|参数|类型|描述

|`InputStreamResource`
|InputStreamResource
|org.springframework.core.io.InputStreamResources输入资源,可通过其getInputStream()方法获取输入流

|===

==== 文件删除
[source,http,options="nowrap"]
----
DELETE /file/delete HTTP/1.1
----

[cols="1,1,4", options="header"]
.请求参数
|===
|参数|类型|描述

|`sysCode`
|String
|约定系统编码, #(必填)# ["pms","epm","usercenter","progress","portal","collect"],除此之外的由管理员补充

|`fileGroupId`
|String
|文件组ID,相当于文件夹,36位UUID #(必填)#

|`fileId`
|String
|文件ID,36位UUID #(必填)#

|===

[cols="1,1,4", options="header"]
.响应结果
|===
|参数|类型|描述

|`Response`
|Response
|com.lensyn.common.utils.system.response.Response删除结果文字描述

|===

=== FeignClient示例代码
[source,java]
----
package com.suncd.pms.framework.service.common;

import com.lensyn.common.utils.system.response.Response;
import org.springframework.cloud.netflix.feign.FeignClient;
import org.springframework.core.io.InputStreamResource;
import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import java.io.InputStream;

/**
 * 功能：文件服务
 *
 * @author qust
 * @version 1.0  2017-08-22
 */
@FeignClient(name = "oss-api-service",fallback = FileServiceFallbackImpl.class)
public interface FileService {
    /**
     * 文件上传 - MultipartFile类型
     * @param sysCode     系统编码-对应Hbase的tableName
     * @param fileGroupId 文件组UUID
     * @param fileId      文件UUID
     * @param file        MultipartFile
     * @return Response
     */
    @RequestMapping(value = "/file/upload/multiPartFile",method = RequestMethod.POST,consumes = {MediaType.MULTIPART_FORM_DATA_VALUE})
    Response upload(@RequestParam("sysCode") String sysCode,
                    @RequestParam("fileGroupId") String fileGroupId,
                    @RequestParam("fileId") String fileId,
                    @RequestPart("file") MultipartFile file);
    /**
     * 文件上传 - byte[]类型
     * @param sysCode     系统编码-对应Hbase的tableName
     * @param fileGroupId 文件组UUID
     * @param fileId      文件UUID
     * @param fileName    文件名称,如: 质量报告.docx
     * @param file        byte[]文件字节对象
     * @return Response
     */
    @RequestMapping(value = "/file/upload/bytes",method = RequestMethod.POST)
    Response upload(@RequestParam("sysCode") String sysCode,
                    @RequestParam("fileGroupId") String fileGroupId,
                    @RequestParam("fileId") String fileId,
                    @RequestParam("fileName") String fileName,
                    @RequestParam("file") byte[] file);
    /**
     * 文件上传 - InputStream类型
     * @param sysCode     系统编码-对应Hbase的tableName
     * @param fileGroupId 文件组UUID
     * @param fileId      文件UUID
     * @param fileName    文件名称,如: 质量报告.docx
     * @param file        InputStream输入流
     * @return Response
     */
    @RequestMapping(value = "/file/upload/inputStream",method = RequestMethod.POST)
    Response upload(@RequestParam("sysCode")String sysCode,
                    @RequestParam("fileGroupId") String fileGroupId,
                    @RequestParam("fileId") String fileId,
                    @RequestParam("fileName")String fileName,
                    @RequestParam("file") InputStream file);
    /**
     * 文件下载
     *
     * @param sysCode     系统编码-对应Hbase的tableName
     * @param fileGroupId 文件组UUID
     * @param fileId      文件UUID
     * @return InputStreamResource 输入流
     */
    @RequestMapping(value = "/file/download",method = RequestMethod.POST)
    InputStreamResource download(@RequestParam("sysCode") String sysCode,
                                 @RequestParam("fileGroupId") String fileGroupId,
                                 @RequestParam("fileId") String fileId);
    /**
     * 文件删除
     *
     * @param sysCode     系统编码-对应Hbase的tableName
     * @param fileGroupId 文件组UUID
     * @param fileId      文件UUID
     * @return Response
     */
    @RequestMapping(value = "/file/delete",method = RequestMethod.DELETE)
    Response delete(@RequestParam("sysCode") String sysCode,
                    @RequestParam("fileGroupId") String fileGroupId,
                    @RequestParam("fileId") String fileId);
    /**
     * 获取文件信息
     *
     * @param sysCode     系统编码-对应Hbase的tableName
     * @param fileGroupId 文件组UUID
     * @param fileId      文件UUID
     * @return Response 文件信息
     */
    @RequestMapping(value = "/file/info",method = RequestMethod.GET)
    Response fileInfo(@RequestParam("sysCode") String sysCode,
                      @RequestParam("fileGroupId") String fileGroupId,
                      @RequestParam("fileId") String fileId);

}

----

== 结束



